-- MySQL Script generated by MySQL Workbench
-- Tue 29 Sep 2020 01:05:22 AM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stube
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stube` DEFAULT CHARACTER SET utf8 ;
USE `stube` ;

-- -----------------------------------------------------
-- Table `stube`.`usuaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stube`.`usuaris` (
  `usuaris_id` INT NOT NULL AUTO_INCREMENT,
  `usuaris_nom` VARCHAR(45) NULL,
  `usuaris_email` VARCHAR(45) NULL,
  `usuaris_pwd` VARCHAR(45) NULL,
  `usuaris_creat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usuaris_modificat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`usuaris_id`),
  UNIQUE INDEX `usuaris_email_UNIQUE` (`usuaris_email` ASC),
  UNIQUE INDEX `usuaris_nom_UNIQUE` (`usuaris_nom` ASC),
  INDEX `email_idx` (`usuaris_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stube`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stube`.`videos` (
  `videos_id` INT NOT NULL AUTO_INCREMENT,
  `videos_titol` VARCHAR(45) NULL,
  `videos_url` VARCHAR(45) NULL,
  `videos_identificador` VARCHAR(45) NULL,
  `videos_descripcio` VARCHAR(45) NULL,
  `videos_creat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `videos_modificat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuaris_usuaris_id` INT NOT NULL,
  PRIMARY KEY (`videos_id`, `usuaris_usuaris_id`),
  UNIQUE INDEX `videos_titol_UNIQUE` (`videos_titol` ASC),
  UNIQUE INDEX `videos_url_UNIQUE` (`videos_url` ASC),
  UNIQUE INDEX `videos_identificador_UNIQUE` (`videos_identificador` ASC),
  INDEX `fk_videos_usuaris_idx` (`usuaris_usuaris_id` ASC),
  CONSTRAINT `fk_videos_usuaris`
    FOREIGN KEY (`usuaris_usuaris_id`)
    REFERENCES `stube`.`usuaris` (`usuaris_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
