-- MySQL Script generated by MySQL Workbench
-- Tue 29 Sep 2020 01:06:02 AM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vueling
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vueling
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vueling` DEFAULT CHARACTER SET utf8 ;
USE `vueling` ;

-- -----------------------------------------------------
-- Table `vueling`.`avions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vueling`.`avions` (
  `avions_id` INT NOT NULL AUTO_INCREMENT,
  `avions_model` VARCHAR(45) NULL,
  `avions_capacitat` INT NULL,
  `avions_creat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `avions_modificat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`avions_id`),
  UNIQUE INDEX `avions_model_UNIQUE` (`avions_model` ASC),
  INDEX `model_idx` (`avions_model` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vueling`.`seients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vueling`.`seients` (
  `seients_id` INT NOT NULL AUTO_INCREMENT,
  `seients_fila` INT NULL,
  `seients_columna` VARCHAR(1) NULL,
  `seients_passatger` VARCHAR(45) NULL,
  `seients_creat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `seients_modificat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `avions_avions_id` INT NOT NULL,
  PRIMARY KEY (`seients_id`, `avions_avions_id`),
  INDEX `fk_seients_avions_idx` (`avions_avions_id` ASC),
  INDEX `passatger_idx` (`seients_passatger` ASC),
  CONSTRAINT `fk_seients_avions`
    FOREIGN KEY (`avions_avions_id`)
    REFERENCES `vueling`.`avions` (`avions_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
