-- MySQL Script generated by MySQL Workbench
-- Tue 29 Sep 2020 01:03:47 AM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema culdampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema culdampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `culdampolla` DEFAULT CHARACTER SET utf8 ;
USE `culdampolla` ;

-- -----------------------------------------------------
-- Table `culdampolla`.`proveidors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`proveidors` (
  `proveidors_id` INT NOT NULL AUTO_INCREMENT,
  `proveidors_nom` VARCHAR(45) NULL,
  `proveidors_carrer` VARCHAR(45) NULL,
  `proveidors_numero` VARCHAR(45) NULL,
  `proveidors_pis` VARCHAR(45) NULL,
  `proveidors_porta` VARCHAR(45) NULL,
  `proveidors_ciutat` VARCHAR(45) NULL,
  `proveidors_cp` VARCHAR(45) NULL,
  `proveidors_pais` VARCHAR(45) NULL,
  `proveidors_telefon` VARCHAR(9) NULL,
  `proveidors_fax` VARCHAR(9) NULL,
  `proveidors_nif` VARCHAR(45) NULL,
  `proveidors_creat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `proveidors_modificat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`proveidors_id`),
  UNIQUE INDEX `proveidors_nom_UNIQUE` (`proveidors_nom` ASC),
  UNIQUE INDEX `proveidors_telefon_UNIQUE` (`proveidors_telefon` ASC),
  UNIQUE INDEX `proveidors_fax_UNIQUE` (`proveidors_fax` ASC),
  UNIQUE INDEX `proveidors_nif_UNIQUE` (`proveidors_nif` ASC),
  INDEX `proveidors_carrer_idx` (`proveidors_carrer` ASC),
  INDEX `proveidors_ciutat_idx` (`proveidors_ciutat` ASC),
  INDEX `proveidors_cp_idx` (`proveidors_cp` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culdampolla`.`ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`ulleres` (
  `ulleres_id` INT NOT NULL AUTO_INCREMENT,
  `ulleres_marca` VARCHAR(45) NULL,
  `ulleres_model` VARCHAR(45) NULL,
  `ulleres_vidres-graduacio` VARCHAR(45) NULL,
  `ulleres_vidres-color` VARCHAR(45) NULL,
  `ulleres_muntura` VARCHAR(45) NULL,
  `ulleres_muntura-color` VARCHAR(45) NULL,
  `proveidors_proveidors_id` INT NOT NULL,
  `ulleres_creat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `ulleres_modificat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ulleres_id`, `proveidors_proveidors_id`),
  UNIQUE INDEX `ulleres_model_UNIQUE` (`ulleres_model` ASC),
  INDEX `ulleres_marca_idx` (`ulleres_marca` ASC),
  INDEX `fk_ulleres_proveidors1_idx` (`proveidors_proveidors_id` ASC),
  CONSTRAINT `fk_ulleres_proveidors1`
    FOREIGN KEY (`proveidors_proveidors_id`)
    REFERENCES `culdampolla`.`proveidors` (`proveidors_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culdampolla`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`clients` (
  `clients_id` INT NOT NULL AUTO_INCREMENT,
  `clients_nom` VARCHAR(45) NULL,
  `clients_adreça` VARCHAR(45) NULL,
  `clients_telefon` VARCHAR(9) NULL,
  `clients_email` VARCHAR(45) NULL,
  `clients_data-registre` DATETIME NULL,
  `clients_modificat` DATETIME NULL,
  PRIMARY KEY (`clients_id`),
  UNIQUE INDEX `clients_nom_UNIQUE` (`clients_nom` ASC),
  UNIQUE INDEX `clients_telefon_UNIQUE` (`clients_telefon` ASC),
  UNIQUE INDEX `clients_email_UNIQUE` (`clients_email` ASC),
  UNIQUE INDEX `clients_adreça_UNIQUE` (`clients_adreça` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culdampolla`.`empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`empleats` (
  `empleats_id` INT NOT NULL AUTO_INCREMENT,
  `empleats_nom` VARCHAR(45) NULL,
  `empleats_creat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `empleats_modificat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`empleats_id`),
  UNIQUE INDEX `empleats_nom_UNIQUE` (`empleats_nom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culdampolla`.`compres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`compres` (
  `compres_id` INT NOT NULL AUTO_INCREMENT,
  `compres_referencia` VARCHAR(45) NULL,
  `compres_data` DATETIME NULL,
  `clients_clients_id` INT NOT NULL,
  `empleats_empleats_id` INT NOT NULL,
  `compres_creat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `compres_modificat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`compres_id`, `clients_clients_id`, `empleats_empleats_id`),
  INDEX `fk_compres_clients_idx` (`clients_clients_id` ASC),
  INDEX `fk_compres_empleats1_idx` (`empleats_empleats_id` ASC),
  UNIQUE INDEX `compres_referencia_UNIQUE` (`compres_referencia` ASC),
  CONSTRAINT `fk_compres_clients`
    FOREIGN KEY (`clients_clients_id`)
    REFERENCES `culdampolla`.`clients` (`clients_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_compres_empleats1`
    FOREIGN KEY (`empleats_empleats_id`)
    REFERENCES `culdampolla`.`empleats` (`empleats_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culdampolla`.`compres_has_ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`compres_has_ulleres` (
  `compres_compres_id` INT NOT NULL,
  `compres_clients_clients_id` INT NOT NULL,
  `ulleres_ulleres_id` INT NOT NULL,
  `compres_has_ulleres_creat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `compres_has_ulleres_modificat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`compres_compres_id`, `compres_clients_clients_id`, `ulleres_ulleres_id`),
  INDEX `fk_compres_has_ulleres_ulleres1_idx` (`ulleres_ulleres_id` ASC),
  INDEX `fk_compres_has_ulleres_compres1_idx` (`compres_compres_id` ASC, `compres_clients_clients_id` ASC),
  CONSTRAINT `fk_compres_has_ulleres_compres1`
    FOREIGN KEY (`compres_compres_id` , `compres_clients_clients_id`)
    REFERENCES `culdampolla`.`compres` (`compres_id` , `clients_clients_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_compres_has_ulleres_ulleres1`
    FOREIGN KEY (`ulleres_ulleres_id`)
    REFERENCES `culdampolla`.`ulleres` (`ulleres_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
