-- MySQL Script generated by MySQL Workbench
-- Tue 29 Sep 2020 01:05:38 AM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema quadres
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quadres
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quadres` DEFAULT CHARACTER SET utf8 ;
USE `quadres` ;

-- -----------------------------------------------------
-- Table `quadres`.`compradors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quadres`.`compradors` (
  `compradors_id` INT NOT NULL AUTO_INCREMENT,
  `compradors_nom` VARCHAR(45) NULL,
  `compradors_cognom` VARCHAR(45) NULL,
  `compradors_dni` VARCHAR(9) NULL,
  `compradors_creat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `compradors_modificat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`compradors_id`),
  INDEX `comprador_idx` (`compradors_cognom` ASC, `compradors_nom` ASC),
  INDEX `comprador_dni` (`compradors_dni` ASC),
  UNIQUE INDEX `compradors_dni_UNIQUE` (`compradors_dni` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quadres`.`quadres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quadres`.`quadres` (
  `quadres_id` INT NOT NULL AUTO_INCREMENT,
  `quadres_nom` VARCHAR(45) NULL,
  `quadres_autor` VARCHAR(45) NULL,
  `quadres_data-quadre` DATETIME NULL,
  `quadres_preu` INT NULL,
  `quadres_data-compra` DATETIME NULL,
  `quadres_creat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `quadres_modificat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `compradors_compradors_id` INT NOT NULL,
  PRIMARY KEY (`quadres_id`, `compradors_compradors_id`),
  INDEX `fk_quadres_compradors_idx` (`compradors_compradors_id` ASC),
  INDEX `quadre_idx` (`quadres_nom` ASC),
  INDEX `autor_idx` (`quadres_autor` ASC),
  CONSTRAINT `fk_quadres_compradors`
    FOREIGN KEY (`compradors_compradors_id`)
    REFERENCES `quadres`.`compradors` (`compradors_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
