-- MySQL Script generated by MySQL Workbench
-- Tue 29 Sep 2020 01:04:10 AM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema xarxasocial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema xarxasocial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xarxasocial` DEFAULT CHARACTER SET utf8 ;
USE `xarxasocial` ;

-- -----------------------------------------------------
-- Table `xarxasocial`.`usuaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xarxasocial`.`usuaris` (
  `usuaris_id` INT NOT NULL AUTO_INCREMENT,
  `usuaris_nom` VARCHAR(45) NULL,
  `usuaris_email` VARCHAR(45) NULL,
  `usuaris_pwd` VARCHAR(45) NULL,
  `usuaris_creat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `fotos_modificat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`usuaris_id`),
  UNIQUE INDEX `usuaris_email_UNIQUE` (`usuaris_email` ASC),
  INDEX `usuaris_nom_idx` (`usuaris_nom` ASC),
  UNIQUE INDEX `usuaris_nom_UNIQUE` (`usuaris_nom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xarxasocial`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xarxasocial`.`fotos` (
  `fotos_id` INT NOT NULL AUTO_INCREMENT,
  `fotos_codi` VARCHAR(45) NULL,
  `fotos_lloc` VARCHAR(45) NULL,
  `fotos_url` VARCHAR(45) NULL,
  `usuaris_usuaris_id` INT NOT NULL,
  `fotos_creat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `fotos_modificat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`fotos_id`, `usuaris_usuaris_id`),
  UNIQUE INDEX `fotos_codi_UNIQUE` (`fotos_codi` ASC),
  UNIQUE INDEX `fotos_url_UNIQUE` (`fotos_url` ASC),
  INDEX `fk_fotos_usuaris1_idx` (`usuaris_usuaris_id` ASC),
  INDEX `fotos_lloc_idx` (`fotos_lloc` ASC),
  CONSTRAINT `fk_fotos_usuaris1`
    FOREIGN KEY (`usuaris_usuaris_id`)
    REFERENCES `xarxasocial`.`usuaris` (`usuaris_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xarxasocial`.`usuaris_has_usuaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xarxasocial`.`usuaris_has_usuaris` (
  `usuaris_usuaris_id` INT NOT NULL,
  `usuaris_usuaris_id1` INT NOT NULL,
  `usuaris_has_usuaris_relacio` VARCHAR(45) NULL,
  `usuaris_has_usuaris_creat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usuaris_has_usuaris_modificat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`usuaris_usuaris_id`, `usuaris_usuaris_id1`),
  INDEX `fk_usuaris_has_usuaris_usuaris2_idx` (`usuaris_usuaris_id1` ASC),
  INDEX `fk_usuaris_has_usuaris_usuaris1_idx` (`usuaris_usuaris_id` ASC),
  INDEX `usuaris_has_usuaris_relacio_idx` (`usuaris_has_usuaris_relacio` ASC),
  CONSTRAINT `fk_usuaris_has_usuaris_usuaris1`
    FOREIGN KEY (`usuaris_usuaris_id`)
    REFERENCES `xarxasocial`.`usuaris` (`usuaris_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuaris_has_usuaris_usuaris2`
    FOREIGN KEY (`usuaris_usuaris_id1`)
    REFERENCES `xarxasocial`.`usuaris` (`usuaris_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
